//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDB.model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Acount : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acount()
        {
            this.Operation = new HashSet<Operation>();
        }
    
        public int IdAcount { get; set; }
        public int IdClient { get; set; }
        public int IdType { get; set; }
        public System.DateTime DateOpen { get; set; }
        public System.DateTime DateClose { get; set; }

        public String DateOp
        {
            get
            {
                return DateOpen.Date.Day.ToString() + "." + DateOpen.Date.Month.ToString() + "." + DateOpen.Date.Year.ToString();
            }
        }

        public String DateCl
        {
            get
            {
                return DateClose.Date.Day.ToString() + "." + DateClose.Date.Month.ToString() + "." + DateClose.Date.Year.ToString();
            }
        }

        public string NameClient
        {
            get
            {
                if (Client != null)
                {
                    return Client.FirstName.Trim() + " " + Client.Name.Trim();
                } else
                {
                    return "";
                }
                
            }
        }
        public int Sum { get; set; }
        public string Garantee { get; set; }
        public string CodeAcount { get; set; }
    
        public virtual AcountType AcountType { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation> Operation { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged([CallerMemberName]string prop = "")
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(prop));
        }
    }
}
