//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDB.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client : ICloneable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Acount = new HashSet<Acount>();
        }
    
        public int IdClient { get; set; }
        private string firstname;

        public string FirstName
        {
            get
            {
                if (firstname != null)
                {
                    return firstname.Trim();
                }
                else return firstname;
                
            }
            set
            {
                firstname = value;

            }
        }

        private string name;

        public string Name
        {
            get
            {
                if (name != null)
                {
                    return name.Trim();
                }
                else return name;
            }
            set
            {
                name = value;

            }
        }
        private string adress;

        public string Adress
        {
            get
            {
                if (adress != null)
                {
                    return adress.Trim();
                }
                else return adress;
            }
            set
            {
                adress = value;
            }
        }

        public int IdCode { get; set; }
        public string Phone { get; set; }
        public System.DateTime DateOfBirdth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acount> Acount { get; set; }

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
