//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDB.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int IdOperation { get; set; }
        public int IdAcount { get; set; }
        public System.DateTime DateOperation { get; set; }

        private string typeOperation;
        public string TypeOperation {
            get
            {
                if(typeOperation!= null)
                {
                    return typeOperation.Trim();
                }
                else
                {
                    return typeOperation;
                }
            }
            set
            {
                typeOperation = value;
            }
        }
        public int SumOperation { get; set; }
    
        public virtual Acount Acount { get; set; }
    }
}
